### ISSUE TITLE
Travis build configuration enhancement

### ISSUE THREAD

**Issue by sleshJdev** [itechartbigdatalab/NY-Accidents-Rate#51]
Hi, 

Could you please add this piece of configuration into your .travis.yml

```
branches:
  only: 
    - master
```

to enable builds only for master and prs

Thanks

**Comment by VladimirBaklan** [comment]
Done

https://github.com/itechartbigdatalab/NY-Accidents-Rate/pull/53

**Comment by VladimirBaklan** [comment]
Is all ok?

**Comment by sleshJdev** [comment]
Yup, thanks
