### ISSUE TITLE
Potentially accuracy issue caused by wrong hash calculations 

### ISSUE THREAD

**Issue by sleshJdev** [itechartbigdatalab/NY-Accidents-Rate#6]
Hi,

I left a [comment](https://github.com/itechartbigdatalab/NY-Accidents-Rate/pull/4#discussion_r286459438). PR is merged but nevertheless. I suspect it may cause to not very accurate search. Could you please take a look?

Thanks

**Comment by sleshJdev** [comment]
You said that you ignore seconds when parse timestamp but keep milliseconds what's idea? Could please clarify?

**Comment by VladimirBaklan** [comment]
We have information in dataset in format year:month:day:hour:minutes. And to create hash we drop minutes value, so, we haven't got seconds and milliseconds. Perhaps Alexander has a more detailed explanation.

**Comment by sleshJdev** [comment]
I see, thanks

**Comment by sleshJdev** [comment]
I guess the issue can be closed. @AlexKostritsa ?

**Comment by AlexKostritsa** [comment]
Yes, all as Vladimir said
