### ISSUE TITLE
Use default behaviour of slick to set up database connection pool

### ISSUE THREAD

**Issue by sleshJdev** [itechartbigdatalab/NY-Accidents-Rate#8]
Hi

There is great [feature](http://slick.lightbend.com/doc/3.3.0/database.html#postgresql) in slick that helps you reduce [verbose code](https://github.com/itechartbigdatalab/NY-Accidents-Rate/blob/master/src/main/scala/com/itechart/ny_accidents/database/NYDataDatabase.scala) and make it more flexible and clear. Let's try to apply it in your project. 

Thanks

**Comment by sleshJdev** [comment]
Any updates about that?

**Comment by AlexKostritsa** [comment]
I will read about it now
